ersion: "3.2"
services:
  weather-db:
    container_name: weather-db
    image: postgres:latest
    env_file:
      - ./postgres-db.env
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    networks:
      - default